Args=--initialize-at-run-time=org.eclipse.jgit.util.FS$FileStoreAttributes \
     --initialize-at-run-time=org.eclipse.jgit.internal.storage.file.WindowCache \
     --initialize-at-run-time=org.eclipse.jgit.lib.RepositoryCache \
     -H:+ReportExceptionStackTraces
