package org.treblereel.mcp.core;

import java.io.IOException;
import java.util.*;
import io.quarkus.arc.processor.*;
import org.jboss.jandex.*;
import org.treblereel.mcp.model.*;

public final class BeanResolver {

    private BeanResolver() {}

    public record ResolutionResult(
            List<BeanRecord> beans,
            List<InjectionPointRecord> injectionPoints,
            List<DependencyRecord> dependencies,
            Map<String, Integer> classNameToId
    ) {}

    /**
     * CDI annotation classes that must be present in the Jandex index
     * for Arc's BeanProcessor to resolve qualifiers and injection points.
     */
    private static final List<Class<?>> CDI_API_CLASSES = List.of(
            jakarta.enterprise.inject.Default.class,
            jakarta.enterprise.inject.Any.class,
            jakarta.enterprise.inject.Alternative.class,
            jakarta.enterprise.context.ApplicationScoped.class,
            jakarta.enterprise.context.RequestScoped.class,
            jakarta.enterprise.context.SessionScoped.class,
            jakarta.enterprise.context.Dependent.class,
            jakarta.enterprise.context.NormalScope.class,
            jakarta.inject.Inject.class,
            jakarta.inject.Qualifier.class,
            jakarta.inject.Singleton.class,
            jakarta.inject.Named.class,
            jakarta.annotation.Priority.class,
            jakarta.interceptor.Interceptor.class,
            jakarta.interceptor.InterceptorBinding.class,
            jakarta.interceptor.AroundInvoke.class,
            jakarta.interceptor.InvocationContext.class
    );

    public static ResolutionResult resolve(Index applicationIndex) {
        IndexView index = buildCompositeIndex(applicationIndex);

        BeanProcessor processor = BeanProcessor.builder()
                .setComputingBeanArchiveIndex(index)
                .setImmutableBeanArchiveIndex(index)
                .setApplicationIndex(index)
                .setOutput(resource -> { /* no-op: we don't need generated bytecode */ })
                .build();

        BeanDeployment deployment;
        try {
            processor.registerCustomContexts();
            processor.registerScopes();
            BeanRegistrar.RegistrationContext registrationContext = processor.registerBeans();
            processor.registerSyntheticInjectionPoints(registrationContext);
            processor.registerSyntheticObservers();
            processor.synthesisFinished();
            processor.initialize(transformer -> { /* no-op */ }, Collections.emptyList());
            deployment = processor.getBeanDeployment();
        } catch (Exception e) {
            throw new RuntimeException("CDI resolution failed", e);
        }

        Map<String, Integer> classNameToId = new HashMap<>();
        List<BeanRecord> beanRecords = new ArrayList<>();
        List<InjectionPointRecord> ipRecords = new ArrayList<>();
        List<DependencyRecord> depRecords = new ArrayList<>();

        int beanIdSeq = 1;
        Map<BeanInfo, Integer> beanIdMap = new IdentityHashMap<>();

        List<BeanInfo> allBeans = new ArrayList<>(deployment.getBeans());
        allBeans.addAll(deployment.getInterceptors());
        allBeans.addAll(deployment.getDecorators());

        for (BeanInfo bean : allBeans) {
            int beanId = beanIdSeq++;
            beanIdMap.put(bean, beanId);

            String className = bean.getBeanClass().toString();
            String kind = beanKind(bean);
            String scope = bean.getScope().getDotName().toString();
            List<String> qualifiers = bean.getQualifiers().stream()
                    .map(ann -> "@" + ann.name().withoutPackagePrefix())
                    .toList();
            List<String> stereotypes = bean.getStereotypes().stream()
                    .map(s -> "@" + s.getName().withoutPackagePrefix())
                    .toList();
            Set<Type> types = bean.getTypes();
            List<String> beanTypes = types.stream()
                    .map(t -> t.name().toString())
                    .toList();
            boolean isAlternative = bean.isAlternative();
            Integer priority = bean.getPriority();

            Integer declaringClassId = null;
            String memberName = null;
            if (bean.isProducerMethod()) {
                memberName = bean.getTarget()
                        .map(t -> t.asMethod().name())
                        .orElse(null);
                BeanInfo declaring = bean.getDeclaringBean();
                if (declaring != null) {
                    declaringClassId = classNameToId.computeIfAbsent(
                            declaring.getBeanClass().toString(),
                            k -> classNameToId.size() + 1);
                }
            } else if (bean.isProducerField()) {
                memberName = bean.getTarget()
                        .map(t -> t.asField().name())
                        .orElse(null);
                BeanInfo declaring = bean.getDeclaringBean();
                if (declaring != null) {
                    declaringClassId = classNameToId.computeIfAbsent(
                            declaring.getBeanClass().toString(),
                            k -> classNameToId.size() + 1);
                }
            }

            int classId = classNameToId.computeIfAbsent(className, k -> classNameToId.size() + 1);

            beanRecords.add(new BeanRecord(
                    beanId, classId, kind,
                    "@" + scope.substring(scope.lastIndexOf('.') + 1),
                    qualifiers, stereotypes, isAlternative, priority,
                    null, declaringClassId, memberName, beanTypes
            ));
        }

        int ipIdSeq = 1;
        for (BeanInfo bean : allBeans) {
            Integer ownerBeanId = beanIdMap.get(bean);
            if (ownerBeanId == null) continue;

            for (InjectionPointInfo ip : bean.getAllInjectionPoints()) {
                int ipId = ipIdSeq++;
                String targetType = ip.getRequiredType().name().toString();
                List<String> ipQualifiers = ip.getRequiredQualifiers().stream()
                        .map(ann -> "@" + ann.name().withoutPackagePrefix())
                        .toList();

                AnnotationTarget target = ip.getTarget();
                String fieldName = null;
                String ipKind = "FIELD";
                if (target != null) {
                    if (ip.isField()) {
                        fieldName = target.asField().name();
                        ipKind = "FIELD";
                    } else if (ip.isParam()) {
                        if (target.kind() == AnnotationTarget.Kind.METHOD) {
                            MethodInfo method = target.asMethod();
                            if ("<init>".equals(method.name())) {
                                ipKind = "CONSTRUCTOR_PARAM";
                            } else {
                                ipKind = "METHOD_PARAM";
                            }
                            fieldName = method.name();
                        } else {
                            ipKind = "METHOD_PARAM";
                            fieldName = target.toString();
                        }
                    }
                }

                BeanInfo resolved = ip.hasResolvedBean() ? ip.getResolvedBean() : null;
                Integer resolvedBeanId = resolved != null ? beanIdMap.get(resolved) : null;
                boolean isAmbiguous = !ip.hasResolvedBean();

                ipRecords.add(new InjectionPointRecord(
                        ipId, ownerBeanId, ipKind, targetType, ipQualifiers,
                        fieldName, resolvedBeanId, isAmbiguous
                ));

                if (resolvedBeanId != null) {
                    int fromClassId = classNameToId.getOrDefault(bean.getBeanClass().toString(), -1);
                    String resolvedClassName = resolved.getBeanClass().toString();
                    int toClassId = classNameToId.computeIfAbsent(resolvedClassName, k -> classNameToId.size() + 1);

                    depRecords.add(new DependencyRecord(fromClassId, toClassId, "CDI_INJECT", ipId));
                }
            }
        }

        return new ResolutionResult(beanRecords, ipRecords, depRecords, classNameToId);
    }

    /**
     * Creates a composite index that includes the application's classes
     * plus essential CDI API annotations required by Arc's BeanProcessor.
     */
    private static IndexView buildCompositeIndex(Index applicationIndex) {
        Indexer cdiIndexer = new Indexer();
        for (Class<?> cls : CDI_API_CLASSES) {
            try {
                cdiIndexer.indexClass(cls);
            } catch (IOException e) {
                // annotation class not on classpath — skip
            }
        }
        Index cdiIndex = cdiIndexer.complete();
        return CompositeIndex.create(applicationIndex, cdiIndex);
    }

    private static String beanKind(BeanInfo bean) {
        if (bean.isInterceptor()) return "INTERCEPTOR";
        if (bean.isDecorator()) return "DECORATOR";
        if (bean.isProducerMethod()) return "PRODUCER_METHOD";
        if (bean.isProducerField()) return "PRODUCER_FIELD";
        if (bean.isSynthetic()) return "SYNTHETIC";
        return "CLASS";
    }
}
