quarkus.mcp.server.server-info.name=quill
quarkus.mcp.server.server-info.version=1.0.0-SNAPSHOT

# Native image
quarkus.native.additional-build-args=--initialize-at-run-time=org.eclipse.jgit.util.FS\\$FileStoreAttributes\\,org.eclipse.jgit.internal.storage.file.WindowCache\\,org.eclipse.jgit.lib.RepositoryCache
quarkus.native.resources.includes=com/knuddels/jtokkit/*.tiktoken,org/eclipse/jgit/internal/*.properties
